# Generated by Django 4.2.23 on 2025-07-15 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('predicted_moisture', models.FloatField()),
                ('current_moisture', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('precipitation', models.FloatField(default=0.0)),
                ('prediction_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(unique=True)),
                ('sensor_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('soil_moisture_percent', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('battery_voltage', models.FloatField()),
                ('irrigation_action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'soil_moisture_records',
            },
        ),
    ]
