# Generated by Django 4.2.23 on 2025-07-16 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techniciandashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSoilMoisturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location of the prediction', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of prediction')),
                ('current_moisture', models.FloatField(help_text='Current soil moisture percentage')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('precipitation', models.FloatField(default=0.0, help_text='Precipitation in mm')),
                ('predicted_category', models.CharField(help_text='Predicted moisture category', max_length=20)),
                ('predicted_moisture_value', models.FloatField(help_text='Predicted moisture value (%)')),
                ('confidence', models.FloatField(blank=True, help_text='Prediction confidence score', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated time')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', 'timestamp'], name='techniciand_locatio_2c8d02_idx')],
            },
        ),
    ]
